export default [{
  title: 'Tree',
  src: `../../static/images/home/tree.png`,
  link: `/tree`,
  index: 1
}, {
  title: 'Gird',
  src: `../../static/images/gird/gird.png`,
  link: `/girddemo`,
  index: 2
}, {
  title: 'tabbar',
  src: `../../static/images/tabbar/tabs.png`,
  link: `/tabbar`,
  index: 3
}, {
  title: 'header',
  src: `../../static/images/header/titlebar_icon_back.svg`,
  link: `/header`,
  index: 4
}, {
  title: 'ActionSheet',
  src: `../../static/images/ActionSheet/ActionSheet.png`,
  link: `/ActionSheet`,
  index: 5
}, {
  title: 'Button',
  src: `../../static/images/button/button.png`,
  link: `/Button`,
  index: 6
}, {
  title: 'Drag',
  src: `../../static/images/drag/drag.png`,
  link: `/drag`,
  index: 7
}, {
  title: 'DragToSort',
  src: `../../static/images/dragToSort/drag_to_sort.png`,
  link: `/DragToSort`,
  index: 8
}, {
  title: '开发中',
  src: `../../static/images/develop.png`,
  link: `/other`,
  index: 9
}]
